
# db/migrations/script.py.mako
"""add_payment_and_reminder_fields

Revision ID: 8cd3bef4a33c
Revises: 001_initial
Create Date: 2026-02-17 09:37:22.644011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cd3bef4a33c'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('payment_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('appointments', sa.Column('payment_receipt_url', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('appointments', sa.Column('payment_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('appointments', sa.Column('reminder_sent', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'reminder_sent')
    op.drop_column('appointments', 'payment_confirmed_at')
    op.drop_column('appointments', 'is_paid')
    op.drop_column('appointments', 'payment_receipt_url')
    op.drop_column('appointments', 'payment_amount')
    # ### end Alembic commands ###
